### PR TITLE
Added Enter and Escape Action Handeling

### PR DESCRIPTION
**Pull request by MLK97**
If user is in one of the three text fields, pressing enter or escape triggers the common known sequence.
Enter: Applies effect and closes window
Escape: Just close window

This was requested by issue #17

### CODE REVIEW

**Comment by MLK97** [comment]
I can add the behavior, that enter and escape will trigger the same effect without having selected one of the textfields. I don't know if this is behavior that you wish for the plug-in

**Comment by jeetee** [comment]
Auch.. you've completely crossed my local development of today.. sorry

Feel free to review my approach, which is done by setting the key handler directly on the plugin QQuickView itself. According to https://doc.qt.io/qt-5/qml-qtquick-keys.html#key-handling-priorities it should capture all events from all nested input fields that aren't explicitly handled there (which should be the case for both Escape as well as Return/Enter settings.

But I think it still only works if you're focussed into one of those input fields and not just as a general capture all.

**Comment by jeetee** [comment]
If you want, I can probably still record merge your patch, so you'll get the author credit for it as well

**Comment by MLK97** [comment]
> But I think it still only works if you're focussed into one of those input fields and not just as a general capture all.

Just tested it. And you are correct you need to have an inputfield selected. I found a way that the shortcuts always work as long as the window is focused. I can PR that if you want!

**Comment by jeetee** [comment]
Please do; I'll probably only merge tomorrow as its quite late over here now

**Pull request closed without merging**
